"""initial migration

Revision ID: e90ced86cc0a
Revises:
Create Date: 2023-06-13 11:24:26.192937

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e90ced86cc0a"
down_revision = None
branch_labels = None
depends_on = None

ITEM_STATUS = postgresql.ENUM(
    "ADDED", "SCANNED", "FAULT", "ABSENT", name="item_status"
)

ORDER_STATUS = postgresql.ENUM(
    "IS_FORMING", "IS_COLLECTING", "IS_READY", name="order_status"
)

SESSION_STATUS = postgresql.ENUM(
    "OPENED", "CLOSED_SUCCESS", "CLOSED_PROBLEM", name="session_status"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cartons",
        sa.Column("carton_type", sa.TEXT(), nullable=False),
        sa.Column("barcode", sa.TEXT(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("carton_type", name="uc_carton_type"),
    )
    op.create_table(
        "orders",
        sa.Column("create_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("status", ORDER_STATUS, nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompts",
        sa.Column("prompt", sa.TEXT(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prompt", name="uc_prompt"),
    )
    op.create_table(
        "skus",
        sa.Column("sku", sa.TEXT(), nullable=False),
        sa.Column("barcode", sa.TEXT(), nullable=False),
        sa.Column("img", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku", name="uc_sku"),
    )
    op.create_table(
        "items",
        sa.Column("status", ITEM_STATUS, nullable=False),
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("box_id", sa.UUID(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("count > 0", name="check_count_positive"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recommended_carton",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("carton_id", sa.UUID(), nullable=False),
        sa.Column("box_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["carton_id"],
            ["cartons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("order_id", "carton_id", "id"),
    )
    op.create_table(
        "selected_carton",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("carton_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["carton_id"],
            ["cartons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("order_id", "carton_id", "id"),
    )
    op.create_table(
        "sessions",
        sa.Column("create_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("end_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status", SESSION_STATUS, nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "item_prompt",
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["prompts.id"],
        ),
        sa.PrimaryKeyConstraint("item_id", "prompt_id", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item_prompt")
    op.drop_table("sessions")
    op.drop_table("selected_carton")
    op.drop_table("recommended_carton")
    op.drop_table("items")
    op.drop_table("skus")
    op.drop_table("prompts")
    op.drop_table("orders")
    op.drop_table("cartons")
    ITEM_STATUS.drop(op.get_bind())
    ORDER_STATUS.drop(op.get_bind())
    SESSION_STATUS.drop(op.get_bind())
    # ### end Alembic commands ###
