"""initial migration

Revision ID: 9454b5294dd3
Revises: 
Create Date: 2023-06-11 21:23:12.201947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9454b5294dd3"
down_revision = None
branch_labels = None
depends_on = None

ITEM_STATUS = postgresql.ENUM(
    "ADDED", "SCANNED", "FAULT", "ABSENT", name="item_status"
)

ORDER_STATUS = postgresql.ENUM(
    "IS_FORMING", "IS_COLLECTING", "IS_READY", name="order_status"
)

SESSION_STATUS = postgresql.ENUM(
    "OPENED", "CLOSED_SUCCESS", "CLOSED_PROBLEM", name="session_status"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # item_status.create(op.get_bind())
    # order_status.create(op.get_bind())
    # session_status.create(op.get_bind())

    op.create_table(
        "cartons",
        sa.Column("carton_type", sa.TEXT(), nullable=False),
        sa.Column("barcode", sa.TEXT(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompts",
        sa.Column("prompt", sa.TEXT(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skus",
        sa.Column("sku", sa.TEXT(), nullable=False),
        sa.Column("barcode", sa.TEXT(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "items",
        sa.Column("status", ITEM_STATUS, nullable=False),
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "item_prompt",
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["prompts.id"],
        ),
        sa.PrimaryKeyConstraint("item_id", "prompt_id", "id"),
    )
    op.create_table(
        "orders",
        sa.Column("status", ORDER_STATUS, nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recommended_carton",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("carton_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["carton_id"],
            ["cartons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("order_id", "carton_id", "id"),
    )
    op.create_table(
        "selected_carton",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("carton_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["carton_id"],
            ["cartons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("order_id", "carton_id", "id"),
    )
    op.create_table(
        "sessions",
        sa.Column("start_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("end_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status", SESSION_STATUS, nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    op.drop_table("selected_carton")
    op.drop_table("recommended_carton")
    op.drop_table("orders")
    op.drop_table("item_prompt")
    op.drop_table("items")
    op.drop_table("skus")
    op.drop_table("prompts")
    op.drop_table("cartons")
    ITEM_STATUS.drop(op.get_bind())
    ORDER_STATUS.drop(op.get_bind())
    SESSION_STATUS.drop(op.get_bind())
    # ### end Alembic commands ###
